// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drevmruglvptbjvxntzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZXZtcnVnbHZwdGJqdnhudHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjc5MDAsImV4cCI6MjA1MjgwMzkwMH0._gh5IZo8umvDjcfV42N0i3MVf5K-s1p1Kw0l4KHHC_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);